### ISSUE TITLE
Unable to upload bom with secured dependency track

### ISSUE THREAD

**Issue by sherknil** [gsoft-inc/azure-pipelines-dependency-track#27]
Hello,
I am getting below error while uploading bom.json to dependency track with https.
I am able to upload bom to dependency track with http.

_Starting: Upload BOM to Dependency Track
==============================================================================
Task         : Upload BOM to Dependency Track
Description  : Upload a BOM file to Dependency Track platform.
Version      : 1.12.0
Author       : Edouard Shaar
Help         : 
==============================================================================
Reading certificate from location: C:\Agents\Root-CA.cer
Reading BOM from location: C:\Agents\bom.json
Starting BOM upload to Dependency Track at url: https://hc-sec-tools.hcwtestsaas.local:8445/
Finished task execution with error - Error: Uploading the BOM to Dependency Track Failed: {"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}
##[error]Uploading the BOM to Dependency Track Failed: {"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}_

**Comment by Zargath** [comment]
Hi @sherknil, 

This error happens when the certificate you are providing and the one used for the HTTPS configuration of Dependency track don't match. Basically, the certificate you provided is not part of the chain of the certificate used to configure HTTPS of your DTrack installation.

Thanks,
Edouard

**Comment by sherknil** [comment]
Thanks for the reply!

This is resolved now.
